<?php

return [
    'plans' => [
        'starter' => [
            'name' => 'Starter',
            'price' => 0,
            'billing_interval' => null,
            'description' => 'Mulai rapikan invoice bisnis pertamamu.',
            'sort_order' => 10,
            'is_recommended' => false,
            'features' => [
                'invoice.create' => true,
                'invoice.email_delivery' => true,
                'whatsapp.reminder' => false,
                'bank.integration' => false,
                'reconciliation.automatic' => false,
                'tax.monthly_report' => false,
                'tax.automated_audit' => false,
                'tax.annual_report' => false,
                'multi_store' => false,
                'community.support' => true,
                'ai.reminder_draft' => true,
                'ai.insights' => true,
                'ai.reconciliation' => false,
                'ai.deep_analysis' => false,
                'ai.on_demand_refresh' => false,
                'ai.reminder_tones' => false,
                'anomaly.detection' => false,
                'ai.anomaly_explanation' => false,
                'marketplace.integration' => false,
            ],
            'limits' => [
                'monthlyInvoices' => 10, 'bankAccounts' => 0, 'stores' => 1,
                'aiCreditsMonthly' => 25, 'aiCreditsDaily' => 3,
                'aiMaxInsights' => 2, 'aiMaxCandidates' => 0, 'aiInsightIntervalDays' => 7,
            ],
            'benefits' => [
                ['label' => 'Maks. 10 invoice / bulan', 'included' => true],
                ['label' => 'Tanpa integrasi bank', 'included' => false],
                ['label' => 'Pengingat via email', 'included' => true],
                ['label' => 'Dukungan komunitas', 'included' => true],
            ],
        ],
        'basic' => [
            'name' => 'Basic',
            'price' => 99000,
            'billing_interval' => 'month',
            'description' => 'Solusi lengkap untuk bisnis menengah.',
            'sort_order' => 20,
            'is_recommended' => false,
            'features' => [
                'invoice.create' => true,
                'invoice.email_delivery' => true,
                'whatsapp.reminder' => true,
                'bank.integration' => true,
                'reconciliation.automatic' => true,
                'tax.monthly_report' => true,
                'tax.automated_audit' => false,
                'tax.annual_report' => false,
                'multi_store' => false,
                'community.support' => true,
                'ai.reminder_draft' => true,
                'ai.insights' => true,
                'ai.reconciliation' => true,
                'ai.deep_analysis' => true,
                'ai.on_demand_refresh' => true,
                'ai.reminder_tones' => true,
                'anomaly.detection' => true,
                'ai.anomaly_explanation' => true,
                'marketplace.integration' => true,
            ],
            'limits' => [
                'monthlyInvoices' => null, 'bankAccounts' => 1, 'stores' => 1,
                'aiCreditsMonthly' => 250, 'aiCreditsDaily' => 30,
                'aiMaxInsights' => 3, 'aiMaxCandidates' => 2, 'aiInsightIntervalDays' => 1,
            ],
            'benefits' => [
                ['label' => 'Unlimited invoice', 'included' => true],
                ['label' => '1 rekening bank', 'included' => true],
                ['label' => 'Pengingat WhatsApp otomatis', 'included' => true],
                ['label' => 'Rekap pajak bulanan', 'included' => true],
                ['label' => 'Pencocokan pembayaran otomatis', 'included' => true],
            ],
        ],
        'pro' => [
            'name' => 'Pro',
            'price' => 299000,
            'billing_interval' => 'month',
            'description' => 'Efisiensi maksimal dengan AI pintar.',
            'sort_order' => 30,
            'is_recommended' => true,
            'features' => [
                'invoice.create' => true,
                'invoice.email_delivery' => true,
                'whatsapp.reminder' => true,
                'bank.integration' => true,
                'reconciliation.automatic' => true,
                'tax.monthly_report' => true,
                'tax.automated_audit' => true,
                'tax.annual_report' => true,
                'multi_store' => true,
                'community.support' => true,
                'ai.reminder_draft' => true,
                'ai.insights' => true,
                'ai.reconciliation' => true,
                'ai.deep_analysis' => true,
                'ai.on_demand_refresh' => true,
                'ai.reminder_tones' => true,
                'anomaly.detection' => true,
                'ai.anomaly_explanation' => true,
                'marketplace.integration' => true,
            ],
            'limits' => [
                'monthlyInvoices' => null, 'bankAccounts' => 3, 'stores' => null,
                'aiCreditsMonthly' => 900, 'aiCreditsDaily' => 100,
                'aiMaxInsights' => 5, 'aiMaxCandidates' => 3, 'aiInsightIntervalDays' => 1,
            ],
            'benefits' => [
                ['label' => 'Semua fitur Basic', 'included' => true],
                ['label' => 'Multi-toko', 'included' => true],
                ['label' => 'Hingga 3 rekening bank', 'included' => true],
                ['label' => 'Deteksi kebocoran arus kas', 'included' => true],
                ['label' => 'Pemeriksaan pajak otomatis', 'included' => true],
                ['label' => 'Laporan pajak tahunan', 'included' => true],
                ['label' => 'Rekomendasi tindakan dari AI', 'included' => true],
            ],
        ],
    ],
];
